global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'study-planner-app'
    static_configs:
      # Use the service name 'app' from docker-compose
      - targets: ['app:3000'] 

  - job_name: 'jenkins'
    metrics_path: '/prometheus'
    static_configs:
      # Keep this as host.docker.internal if Jenkins is outside this compose file
      - targets: ['host.docker.internal:8084']